server:
  port: 8080
  servlet:
    context-path: /school

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  signerKey: "I=yRmvXsAk==mOiTDifCFPI0BDE?sXJrubqhRaO6ZKHvu5bz!yq!ySbcheYlKG!3"
